kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: Create_ConsumerUser1
  namespace: api.studio
  version: '1.0'
  tags: []
spec:
  api:
    $endpoint: "https://env6311743.a-vir-c2.devportal.ipaas.dev.automation.ibm.com/portal"
  request:
    - method: POST
      resource: /rest/v1/users
      headers:
        - key: Content-Type
          value: application/json
        - key: Authorization
          value: Bearer ${mcsp_token}
      auth:
        noauth: true
      assertions:
        $ref: "api.studio:Created-201:1.0"
      payload:
        raw:
          json: "{\r

            \   \"username\": \"ConsumerUser1\",\r

            \   \"password\": \"ConsumerUser1@\",\r

            \   \"email\": \"ConsumerUser1\",\r

            \   \"firstname\": \"ConsumerUser1\"\r

            \ }\r\n"
    - method: PUT
      resource: /rest/v1/groups/7dead6ba-d7f3-321d-a5c9-971dc33b73fd/users
      headers:
        - key: Content-Type
          value: application/json
      auth:
        noauth: true
      assertions:
        $ref: "hari:HariAssertion:1.0"
      payload:
        raw:
          json: '["1d4a465a-3b9a-3b0e-b14d-ae3d08c3b1d9"]'
  environment:
    $ref: hari:HariEnv:1.0
