kind: assertion
apiVersion: api.webmethods.io/beta
metadata:
  name: Forbidden - 403
  namespace: api.studio
  version: '1.0'
  tags: []
spec:
  - name: "403"
    key: code
    action: equals
    value: 403
