kind: environment
apiVersion: api.webmethods.io/beta
metadata:
  name: HariEnv
  namespace: hari
  version: '1.0'
  tags: []
spec:
  variables:
    - key: domain
      isSecret: false
      value: https://devrealm3.devportal-aw-us.webmethods-dev.io/portal/
    - key: mcsp_token
      isSecret: false
      value: eyJraWQiOiJVd183RGlQdmIxV19lU0hSelRsOEdwclYyODZqbEFWekFxLURjSURHRFFRIiwiYWxnIjoiUlMyNTYifQ.eyJuYW1lIjoiRFBPR1dJbnRlZ3JhdGlvbiIsImRpc3BsYXlOYW1lIjoiRFBPR1dJbnRlZ3JhdGlvbiIsImlzcyI6Imh0dHBzOi8vYWNjb3VudC1pYW0ucGxhdGZvcm0udGVzdC5zYWFzLmlibS5jb20vYWNjb3VudC1pYW0vYXBpLzIuMCIsImV4cCI6MTc1Mzg4MjczOSwianRpIjoiSDRtTFFEOHRGNWhreUVHZkFkLTgyZyIsImlhdCI6MTc1Mzg3NTUzOSwibmJmIjoxNzUzODc1NTA5LCJhdWQiOiJTRVJWSUNFLzIwMjUwNjI1LTE5MzQtNTAxMy05MGFiLWMzNzcwMDQxNmE4MyIsImVudGl0eVR5cGUiOiJTRVJWSUNFSUQiLCJzdWIiOiI2YjQwMjU5Yi0zOTE5LTRjNmMtYWJhMy05ZWJkYTg4Y2VlYmYiLCJyb2xlcyI6eyJTRVJWSUNFIjpbIkFQSSBtYW5hZ2VtZW50IGFkbWluIl19LCJhY2NvdW50SWQiOiIyMDI1MDYyNS0xNzU0LTA0NTEtNjA4NS02ZDY4Y2FmMzVjMjkiLCJzdWJzY3JpcHRpb25JZCI6IjIwMjUwNjI1LTE4NTAtNDIxMy0yMDRmLTI1ZDZiYjU0MThhZSIsInVzZWRCeSI6bnVsbCwiYXBpa2V5VWlkIjoiMDM2ODcxY2MtYjA2NC00ZTFmLWI2NzItNjc2MGMxNzEwY2FkIn0.WahI83U9z51TWH1-Cg3fMONDbBNaqebACePuCKGt-98uso5c4zc-vVbTnmyrZfNSGUVS1wr-EGONkECUY6ecTEF-vkHX2rDQsIYpwZKodBYMbVEJTb-VorF8qn_NU8kpwbz99OMoLZKzxJ5tFGQJkARlqPOhv4h8BUMVguo99ZMj_W87DZsi2PjS7Zgv-IIFFYwAbG_udhsndeMmBAF3GwZoOaf9ZoHfrYPdHhtNQPchQHIko3KtKcc10G4RXIfEAJFGJAUUihdEbbNKX6Z0xMIaUJc7XQAiOwHG1j_ONQIanTLTYtMDB8-S_UrExGnwJ5C9lDaVwmqdQG7-fqX-SQ
    - key: api_key
      isSecret: false
      value: azI6MDM2ODcxY2MtYjA2NC00ZTFmLWI2NzItNjc2MGMxNzEwY2FkOk9JQitwRXdNOGVsVGloQlRoWDVWcEhIK1lWM2creFYzWEdMbWk5aENwSVk9
