kind: test
apiVersion: api.webmethods.io/beta
metadata:
  name: MSCP
  namespace: api.studio
  version: '1.0'
  tags: []
spec:
  api:
    $endpoint: "https://account-iam.platform.test.saas.ibm.com/api/2.0/services/202\
      50625-1934-5013-90ab-c37700416a83"
  request:
    - method: POST
      resource: /apikeys/token
      headers:
        - key: Content-Type
          value: application/json
      auth:
        noauth: true
      assertions:
        $ref: "hari:HariAssertion:1.0"
      payload:
        raw:
          json: "{\r

            \  \"apikey\":
            \"azI6MDM2ODcxY2MtYjA2NC00ZTFmLWI2NzItNjc2MGMxNzEwY2FkOk9JQitwRXdNO\
            GVsVGloQlRoWDVWcEhIK1lWM2creFYzWEdMbWk5aENwSVk9\"\r

            }"
  environment:
    $ref: hari:HariEnv:1.0
