kind: assertion
apiVersion: api.webmethods.io/beta
metadata:
  name: 'No Content - 204 '
  namespace: api.studio
  version: '1.0'
  tags: []
spec:
  - name: "204"
    key: code
    action: equals
    value: 204
